### ISSUE TITLE
Implement simple lookup benchmarks to

### ISSUE THREAD

**Issue by ChShersh** [kowainik/containers-backpack#11]
Basically, rewrite benchmarks from this module and them to `map-contrib` package:

* https://github.com/kowainik/vebt/blob/99ad48044248a6ecde03b86f8df06c5466106a9a/benchmark/Main.hs

It's okay to have `Map.Group.Bench.Lookup` module and depend on `gauge` library in `map-contrib`. We're in prototyping stage now, so it's completely okay to have non-optmized dependencies.

**Comment by yigitozkavci** [comment]
I started implementing this, and I have a question:

Do we prefer another package for the execution of benchmarks or can we add it as an executable for a global testing package? By introducing a single test package we can include both [quickCheck specs](https://github.com/kowainik/containers-backpack/pull/34) and benchmarks as separate executables in that package.

**Comment by ChShersh** [comment]
@yigitozkavci I think `containers-sig-benchmarks` as a separate package looks better to me :+1: Once multiple public libraries, this whole situation will become much easier. But for now let's separate different problems into separate packages so later we can rearrange them easily.
