### ISSUE TITLE
Create extra module in `containers-sig-*` packages with default implementations for some functions

### ISSUE THREAD

**Issue by ChShersh** [kowainik/containers-backpack#16]
There's this useful operator:

```haskell
infixl 9 !?
(!?) :: Key k => Map k v -> k -> Maybe v
(!?) m k = lookup k m
```

And probably there exist other useful functions with default implementations. We need to collect such functions and put them near signatures. Though, good naming for module is most difficult part here...

**Comment by vrom911** [comment]
Duplicate of #23
