### ISSUE TITLE
Cleanup `containers-ordered-strict` package implementation by reexporting functions directly from `container` package

### ISSUE THREAD

**Issue by ChShersh** [kowainik/containers-backpack#24]
Like on this slide:

* http://slides.com/shersh/picnic#/10

**Comment by piq9117** [comment]
Hi! I would like to take this on.

**Comment by piq9117** [comment]
i messed up my commits so bad so i closed it 😓 . I'm pretty bad at squashing commits at the moment.

**Comment by ChShersh** [comment]
@piq9117 Don't worry about that! Unfortunately, it's extremely easy to mess up with `git` and then extremely hard to recover. So don't worry about that 🙂

**Comment by ChShersh** [comment]
Closed by #29
